### ISSUE TITLE
Python and RabbitMQ

### ISSUE THREAD

**Issue by ahtesham007** [Gandhinagar-ML-NLP-Group/talks#14]
### Title

Python and RabbitMQ: A Beginner's Guide to Asynchronous Workflows

### Describe your Talk

I will introduce the messaging queue (RabbitMQ), its application, and its benefits. How this message broker can be integrated with Python and its usage with a demo.

### Pre-requisites & reading material

Python understanding is required.

### Time required for the talk

25 - 30 mins

### About you

I am a Software Engineer at L&T Technology Services with over 2.5 years of work experience. I have been designing, developing, and testing software in Python.

LinkedIn - https://www.linkedin.com/in/ahtesham-zaidi/
Blog - https://ahtesham-zaidi.hashnode.dev/

### Availability

June Talk

### Any comments

This will be beginner friendly talk.

**Comment by Ankush-Chander** [comment]
Hi @ahtesham007
Thank you for accepting the invitation to speak at our event.
Yout talk has been scheduled for 22/June/2024 meetup.
