### ISSUE TITLE
Explainability of Chain of Thoughts Reasoning in LLMs

### ISSUE THREAD

**Issue by parth126** [Gandhinagar-ML-NLP-Group/talks#17]
### Title

Explainability of Chain of Thoughts Reasoning in LLMs

### Describe your Talk

This talk will be a discussion of a recent paper on LLM interpretability.

Paper Title: How to think step-by-step: A mechanistic understanding of chain-of-thought reasoning

Authors: [Subhabrata Dutta](https://scholar.google.co.in/citations?hl=en&user=aoaCs08AAAAJ&view_op=list_works&sortby=pubdate), [Joykirat Singh](https://scholar.google.ca/citations?user=DfxaJCUAAAAJ&hl=en), Soumen Chakrabarti](https://scholar.google.co.in/citations?hl=en&user=LfF2zfQAAAAJ&view_op=list_works&sortby=pubdate), [Tanmoy Chakraborty](https://scholar.google.co.in/citations?user=C5S9JnIAAAAJ&hl=en)

Published in Transactions of Machine Learning Research

Link: https://arxiv.org/abs/2402.18312

### Pre-requisites & reading material

A basic understanding of Transformer architecture is preferred
Prior hands-on experience working with the LLMs, with either API or Source code, is preffered

### Time required for the talk

60 mins

### About you

[Parth Mehta](https://www.linkedin.com/in/parthmehta126/) is a NLP Scientist at [Parmonic](https://www.parmonic.com/). In the pre-GPT era he used to spend a lot of time implementing NLP and ML solutions from scratch. In the post-GPT world he tries to outsource as much as possible to LLMs as possible.

### Availability

27/07/2024

**Comment by Ankush-Chander** [comment]
Delivered in [July meetup](https://github.com/Gandhinagar-ML-NLP-Group/talks?tab=readme-ov-file#july)
