### ISSUE TITLE
Enhancing LLMs with Vernacular Language Support  

### ISSUE THREAD

**Issue by Khyat** [Gandhinagar-ML-NLP-Group/talks#18]
### Title

Enhancing LLMs with Vernacular Language Support  

### Describe your Talk

In this session, we will dive into the following topics:

1. Extending Vocabulary: Learn how to use the SentencePiece Tokenizer to expand the original vocabulary of a language model, enabling it to incorporate new tokens specific to Indic languages. 

3. Pre-Training Techniques: Explore the process of running Pre-Training with the newly extended tokenizer, focusing on how Continuous Pre-training differs from traditional methods, and how it helps the model understand these tokens better. 

4. Instruction Fine-Tuning: Discover how Instruction Fine-Tuning is applied post-Pre-Training to enable the model to perform new tasks tailored to user requirements.

5. Benchmarking and Evaluation: We will discuss various techniques to benchmark and evaluate the performance of the language models. 

6. Challenges and Future Directions: We will share the challenges we encountered during our experiments and outline the next steps to further improve Indic language support.

Our experiments have been conducted on Llama-2 and Llama-3, with a specific focus on enhancing Gujarati language support in these base models.

### Pre-requisites & reading material

- Transformers Architecture
- Basic Tokenization methods 
- Llama Family Architecture

### Time required for the talk

90 mins

### About you

**Khyat Anjaria** has been immersed in the machine learning and AI field for the past 5 years, with extensive experience in the telecommunications and HRTech sectors. He is deeply passionate about exploring and researching new topics, with a focus on solving complex problems in the Natural Language Processing (NLP) domain. Currently, Khyat is working as a Machine Learning Engineer at Rootle.ai in Ahmedabad, where he has been making significant contributions over the past 2 years.

**Dixit Trivedi** has been working as a Machine Learning Engineer at Rootle.ai for the past 3 years, based in Ahmedabad. His expertise lies in the HRTech sector, where he has successfully tackled various challenges in the Natural Language Processing domain during his tenure.

### Availability

14/09/2024

### Any comments

If you would like to connect and discuss further then drop us a message on our Linkedin:

[Khyat Anjaria](https://www.linkedin.com/in/khyat-anjaria-939693148/)
[Dixit Trivedi](https://www.linkedin.com/in/dixit-trivedi/)

**Comment by Ankush-Chander** [comment]
Hi @Khyat and Dixit,
Thank you for submitting your proposal.
Let me get me in touch with you early next month for your talk.
