### ISSUE TITLE
[Beginnner] Talk about Embeddings

### ISSUE THREAD

**Issue by vimalsheoranifcp** [Gandhinagar-ML-NLP-Group/talks#2]
### Title

Embeddings - How Models Look at Text

### Describe your Talk

This talk will entail how text is represented as numbers for an NLP task. The start right from the very beginning of introducing the ideas of tokens and vocabularies. Then we move up to simple techniques like One Hot Encoding, moving forward to TF-IDF and then finally onto Vector Embeddings. Everything will be explained using examples in code.

### Pre-requisites & reading material

None

### Time required for the talk

45 mins

### About you

I'm Vimal Sheoran. Machine Learning Engineer at Infocusp Innovations. I've been working in the field of AI for the past 2 years. I'm currently working with large language models and also improving my knowledge about them. https://www.linkedin.com/in/vimalsheoran/

### Availability

17/12/2023

**Comment by Ankush-Chander** [comment]
Hi @vimalsheoranifcp 
Many thanks for your talk proposal.
If you can you share a rough skeleton of the talk, that would be great.

**Comment by Ankush-Chander** [comment]
Hi @vimalsheoranifcp ,
Your talk has been scheduled for [December meetup](https://www.meetup.com/gandhinagar-machine-learning-and-nlp-group/events/297787571/).
Looking forward to it.
