### ISSUE TITLE
Long document summarization using LLMs

### ISSUE THREAD

**Issue by saurabbhsp** [Gandhinagar-ML-NLP-Group/talks#3]
### Title

[Begineer] Document summarization using LLMs

### Describe your Talk

This talk focuses on prompt engineering and using Langchain for document summarization. It also introduces an alternative to summarize long documents using prompt engineering.

We will go over following topics

- Language Model Evolution
- Task Specific Learning
- Chat Models
- Prompt Engineering
- Summarization 
- Language Model Based Summarization
- Prompt-based Summarization
- Challenges with Long Document Summarization

More Details
TBD

### Pre-requisites & reading material

None, Good to have knowledge of Python

### Time required for the talk

30 minutes

### Link to slides/demos

TDA
### About you

I am Saurabh Pradhan. I am Data scientist at Netconomy Gmbh.  I have more than three years of experience with Computer Vision and Machine learning

https://www.linkedin.com/in/saurabh-pradhan/

### Availability

16/12/2023

**Comment by Ankush-Chander** [comment]
Hi @saurabbhsp 
Many thanks for the talk proposal.
Can you please share rough skeleton of the talk. Slides or link to notebook if it"s hands-on.
Also are you available on 17th December (Saturday) to give the talk?

**Comment by Ankush-Chander** [comment]
Hi @saurabbhsp 
Will you be able to give your talk on 13 Jan (2:30 PM - 5:00 PM IST) ?

**Comment by Ankush-Chander** [comment]
Hi @saurabbhsp 
Talk scheduled for 13 January meetup as per discussion.
