### ISSUE TITLE
Building a Language Model [Part 1]

### ISSUE THREAD

**Issue by vimalsheoranifcp** [Gandhinagar-ML-NLP-Group/talks#8]
### Title

Building a Language Model [Part 1]

### Describe your Talk

This talk is a part of a multi-part talk series that will go through the process of how language models are developed. The idea is to start with an intuition for language modelling (i.e next word prediction problem). We will then build upon this using simple models like BoW and move onto deep learning based approaches using ANNs and RNNs. This talk will cover BoW approach and ANN approach. Inspired by Andrej Karpathy's Makemore series.

### Pre-requisites & reading material

Workings of a neural network.

### Time required for the talk

45 mins

### About you

Vimal

### Availability

17/02/2024

**Comment by Ankush-Chander** [comment]
Hi @vimalsheoranifcp 
Talk scheduled for [17th feb meetup](https://event.sessions.us/gandhinagar-ml-nlp/february-meetup)

**Comment by Ankush-Chander** [comment]
Hi @vimalsheoranifcp 
Would you be interested in giving this talk in our April meetup?

**Comment by Ankush-Chander** [comment]
Delivered on 20th April
