### ISSUE TITLE
Deciphering Large Language Models

### ISSUE THREAD

**Issue by parth126** [Gandhinagar-ML-NLP-Group/talks#9]
### Title

Deciphering Large Language Models: One Prompt at a Time

### Describe your Talk

The talk will provide a peek into the world of prompting. This talk is ideal for professionals, academics, and enthusiasts in the field of AI and technology who are keen to explore practical aspects of Large Language Models. 

#### What will be covered:

1. Introduction to LLMs
2. Zero and Few shot prompting
3. Prompt Engineering
4. Fine-tuned vs Pre-trained models
5. Issues and Limitations 

#### What will NOT be covered:

1. Technical Details of LLM Training
2. Hands on coding
3. Statistical or Mathematical Concepts

### Time required for the talk

45 mins

### About you

[Parth Mehta](https://www.linkedin.com/in/parthmehta126/) is a NLP Scientist at [Parmonic](https://www.parmonic.com/). In the pre-GPT era he used to spend a lot of time implementing NLP and ML solutions from scratch. In the post-GPT world he tries to outsource as much as possible to LLMs including a major part of this proposed talk.

### Availability

17/02/2024

**Comment by Ankush-Chander** [comment]
@parth126 Talk scheduled for [17th feb meetup](https://event.sessions.us/gandhinagar-ml-nlp/february-meetup)

**Comment by Ankush-Chander** [comment]
Slides link: [here](https://docs.google.com/presentation/d/1Y8FXSGOWsBxx_2M1honxzh641wHhTGPv/edit?usp=sharing&ouid=116947312537028941667&rtpof=true&sd=true)
